spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      leak-detection-threshold: 15000

base:
  file:
    diretory: /Volumes/Dev/file

example:
  api:
    host: https://501aba27-1165-4da9-a731-874c549d17d1.mock.pstmn.io

logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    jdbc.resultsettable: info
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off
    log4jdbc.log4j2: info