spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

#      driver-class-name: org.h2.Driver

base:
  file:
    diretory: /Volumes/Dev/file

example:
  api:
    host: https://501aba27-1165-4da9-a731-874c549d17d1.mock.pstmn.io

logging:
  level:
    jdbc: off
    root: info
